### ISSUE TITLE
failed to load property file

### ISSUE THREAD

**Issue by chetanJTH** [shankybnl/MobileAutomationFramework#16]
do you know the reason for this error?

![image](https://user-images.githubusercontent.com/48850556/123045936-2120ca00-d419-11eb-96a9-337a6bab54f8.png)

**Comment by shankybnl** [comment]
On line number 3, replace the value of ${os} with android and run again. It
will work.

**Comment by chetanJTH** [comment]
take a look @shankybnl 
![image](https://user-images.githubusercontent.com/48850556/123052994-0b170780-d421-11eb-843f-167748491218.png)

**Comment by chetanJTH** [comment]
I really don't know the reason but it still failed to load properties. @shankybnl 
![image](https://user-images.githubusercontent.com/48850556/123053674-c5a70a00-d421-11eb-99ff-0f89df148662.png)

**Comment by shankybnl** [comment]
"${os}" is to be replaced with "android".  ${os} is a variable that needs to be passed either as android or ios. Below is the explanation:

In case you are executing android tests:

`<parameter name="os" value="android" />`

In case you are executing iOS tests:

`<parameter name="os" value="ios" />`

**Comment by chetanJTH** [comment]
@shankybnl does it require to start appium manually?

**Comment by shankybnl** [comment]
Yes, Appium has to be started manually for now. Although, there is a method `startAppiumServer ` in [CreateSession](https://github.com/shankybnl/MobileAutomationFramework/blob/master/src/main/java/UITestFramework/CreateSession.java) class. But I think that might be outdated with the newer Appium version. You have to check if it still works and then includes it in the `createDriver` method.

**Comment by chetanJTH** [comment]
@shankybnl i have started appium manually and got this 

![image](https://user-images.githubusercontent.com/48850556/123057410-79f65f80-d425-11eb-9740-2e9eaebffb4c.png)

**Comment by shankybnl** [comment]
Are you running the tests on windows? If yes, try starting Appium as administrator on your windows machine then rerun the test.

**Comment by shankybnl** [comment]
If it does not solve the issue, Please share the full logs to debug.

**Comment by chetanJTH** [comment]
check logs here @shankybnl : https://gist.github.com/chetanJTH/b23d2dbbac416cb247a01d4f7c8d7ea5

**Comment by shankybnl** [comment]
As per the logs, It is now failing while launching the app. 

1. Is the Slideshare app successfully installed on the device automatically?
2. Are you using the same Slideshare app that is present in the git repository?

`Encountered internal error running command: Error: Cannot start the 'net.slideshare.mobile' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. Original error: Cannot start the 'net.slideshare.mobile' application. Visit https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/android/activity-startup.md for troubleshooting. 
Original error: **Activity name '.net.slideshare.mobile.ui.SplashActivity'** used to start the app doesn't exist or cannot be launched! Make sure it exists and is a launchable activity
[debug] [35m[W3C][39m     at ADB.startApp (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-adb\lib\tools\apk-utils.js:177:11)
[`

**Comment by shankybnl** [comment]
Was this issue solved @chetanJTH ?

**Comment by chetanJTH** [comment]
@shankybnl : i tried starting appium buy code and got issue. 
![image](https://user-images.githubusercontent.com/48850556/123772812-c3452400-d8e9-11eb-83b8-18c83b866a8f.png)

**Comment by chetanJTH** [comment]
@shankybnl I have started appium programmatically but config file keep failed to load
![image](https://user-images.githubusercontent.com/48850556/123776759-3603ce80-d8ed-11eb-9bfe-f3761cf92358.png)

**Comment by shankybnl** [comment]
Can you please share the content of your testng.xml file?

I hope you are already passing the os value as I have mentioned here : https://github.com/shankybnl/MobileAutomationFramework/issues/16#issuecomment-866600303

**Comment by chetanJTH** [comment]
@shankybnl 
![image](https://user-images.githubusercontent.com/48850556/123899779-744ccc80-d985-11eb-8ba1-e4955442e310.png)

**Comment by chetanJTH** [comment]
@shankybnl 

![image](https://user-images.githubusercontent.com/48850556/123928383-7d509480-d9ab-11eb-8d25-7153e910d0e9.png)

**Comment by shankybnl** [comment]
Hi @chetanJTH , 

I think this issue was resolved. Closing the thread for now. Please feel free to reopen it if you are still facing the issue. Thanks.
