### ISSUE TITLE
Will this framework supports mobile browser automation?

### ISSUE THREAD

**Issue by RollerIn** [shankybnl/MobileAutomationFramework#17]
IS this framework supports mobile browser test automation on android and iOS? like mobile android chrome browser and iOS safari mobile browser>

**Comment by shankybnl** [comment]
Hi @RollerIn ,

It is not supported as of now. Please feel free to create new [idea](https://github.com/shankybnl/MobileAutomationFramework/discussions/categories/ideas) and let me know the requirements. I will look into it and get back to you.

Best,
Shanky
