### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by RollerIn** [shankybnl/MobileAutomationFramework#18]
seems lot of issues while building itself..
![image](https://user-images.githubusercontent.com/17290705/126868934-b6ccffe9-c532-480a-8cce-2ffdce1f5f79.png)
![image](https://user-images.githubusercontent.com/17290705/126868950-0517c35b-753b-4be5-9234-169fefb8bf8f.png)

**Comment by shankybnl** [comment]
Hi,

1. Variables not resolved in the pom.xml should not cause any issue while compiling the project.
2. mysql dependency is added to the pom.xml file and should be resolved with installing dependencies.

Please execute the below commands from the command line to run a test and let me know if you still face any issues:

install all dependencies and compile the project:
`$ mvn clean install`

For android tests 
`$ mvn test -Dos=android -Dsurefire.suiteXmlFiles=testng.xml`

For ios tests:
`mvn test -Dos=iOS -Dsurefire.suiteXmlFiles=testng.xml`

Best,
Shanky

**Comment by RollerIn** [comment]
NO luck but different issue while $ mvn clean install using…its 
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

but JAVA_HOME setup was done and its 
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
can we have any fix for this?

**Comment by shankybnl** [comment]
What output do you see for the below command? Also, which operating system are you using?

`echo $JAVA_HOME`

**Comment by RollerIn** [comment]
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
this is what I can see

**Comment by shankybnl** [comment]
I see many questions on StackOverflow to fix the problem. One of the threads that might help: https://askubuntu.com/questions/157229/java-home-is-not-defined-correctly

**Comment by RollerIn** [comment]
strange thing …dod lot of combinations…nothing is working

**Comment by shankybnl** [comment]
Hi @RollerIn , Sorry for the late reply. Were you able to solve this issue? This seems more of environment setup issue than specific to this framework
