### ISSUE TITLE
pom file : Element systemPropertyVaraibles is not allowed .

### ISSUE THREAD

**Issue by bijaylaxmi11** [shankybnl/MobileAutomationFramework#23]
<img width="838" alt="Screenshot 2021-08-23 at 11 59 01 AM" src="https://user-images.githubusercontent.com/52172280/130388537-163ea0c1-25d7-469b-842a-ede08f8e6db0.png">

**Comment by shankybnl** [comment]
Hi @bijaylaxmi11 ,

These errors won't do any issues when you execute tests. Please run the tests from the command line and let me know if you face any issues:

install all dependencies and compile the project:
`$ mvn clean install`

For android tests
`$ mvn test -Dos=android -Dsurefire.suiteXmlFiles=testng.xml`

For ios tests:
`mvn test -Dos=iOS -Dsurefire.suiteXmlFiles=testng.xml`

Best,
Shanky

**Comment by zpaya** [comment]
I am getting the below error for android tests. Can you please help me with this? @shankybnl 

[ERROR] Unknown lifecycle phase ".suiteXmlFiles=testng.xml". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available life
cycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources
, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [
Help 1]

**Comment by shankybnl** [comment]
@zpaya - If you are running in the PowerShell then try running as below:

`mvn test -Dos=android -"Dsurefire.suiteXmlFiles=testng.xml"`

Other alternatives are mentioned in this thread : https://stackoverflow.com/questions/31166828/how-to-handle-dots-in-powershell-commands

**Comment by zpaya** [comment]
yes able to run with below command
` mvn test -Dos=android -DtestSuite="testng.xml" -e`
