### ISSUE TITLE
Not working for Jdk 16

### ISSUE THREAD

**Issue by zpaya** [shankybnl/MobileAutomationFramework#24]
I am getting below compile error when using JDK 16 and mvn clean install

Maven version - Apache Maven 3.8.1
JDK - Java version: 16.0.1, vendor: Oracle Corporation

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project mobile-automation-framework: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field
 private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @1e191150 -> [Help 1]

**Comment by zpaya** [comment]
I was able to solve this by updating below dependency

<dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.20</version>
            <scope>provided</scope>
        </dependency>

**Comment by shankybnl** [comment]
I have committed the change. It is available in the `master` branch now.

**Comment by smalldishes** [comment]
Thank you very much for sharing the solution @zpaya

**Comment by kongqingtian** [comment]
yes, thanks very much! it also resolved my issue for JDK17.
